-- Script para adicionar colunas necessárias na tabela PRE_APONTAMENTO_RAW

-- 1. Adicionar coluna PROJETO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PRE_APONTAMENTO_RAW') AND name = 'PROJETO')
BEGIN
    ALTER TABLE PRE_APONTAMENTO_RAW ADD PROJETO VARCHAR(50);
    PRINT 'Coluna PROJETO adicionada';
END

-- 2. Adicionar coluna APROVADO_POR
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PRE_APONTAMENTO_RAW') AND name = 'APROVADO_POR')
BEGIN
    ALTER TABLE PRE_APONTAMENTO_RAW ADD APROVADO_POR VARCHAR(20);
    PRINT 'Coluna APROVADO_POR adicionada';
END

-- 3. Adicionar coluna DATA_APROVACAO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PRE_APONTAMENTO_RAW') AND name = 'DATA_APROVACAO')
BEGIN
    ALTER TABLE PRE_APONTAMENTO_RAW ADD DATA_APROVACAO DATETIME;
    PRINT 'Coluna DATA_APROVACAO adicionada';
END

-- 4. Adicionar coluna OBSERVACOES_APROVACAO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PRE_APONTAMENTO_RAW') AND name = 'OBSERVACOES_APROVACAO')
BEGIN
    ALTER TABLE PRE_APONTAMENTO_RAW ADD OBSERVACOES_APROVACAO TEXT;
    PRINT 'Coluna OBSERVACOES_APROVACAO adicionada';
END

-- 5. Adicionar coluna TELEFONE (se não existir)
IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('PRE_APONTAMENTO_RAW') AND name = 'TELEFONE')
BEGIN
    ALTER TABLE PRE_APONTAMENTO_RAW ADD TELEFONE VARCHAR(20);
    PRINT 'Coluna TELEFONE adicionada';
END

-- 6. Verificar estrutura final
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PRE_APONTAMENTO_RAW'
ORDER BY ORDINAL_POSITION;

PRINT 'Script de criação de colunas executado com sucesso!';
